# from gym.envs.registration import register
from envs.cartpole import CartpoleEnv
from envs.vehicle import VehicleLateralEnv
from envs.pendubot import PendubotEnv
from envs.linearized_inverted_pendulum import LinearizedInvertedPendulumEnv
from envs.inverted_pendulum import InvertedPendulumEnv
from envs.powergrid import PowergridEnv
from envs.learned_inverted_pendulum import LearnedInvertedPendulumEnv
from envs.other_inverted_pendulum import OtherInvertedPendulumEnv